# Generated by Django 5.0.2 on 2024-02-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root_music_config', '0005_musiccontainer_stream_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musiccontainer',
            name='replays',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
