# Generated by Django 5.0.2 on 2024-02-25 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root_music_config', '0006_alter_musiccontainer_replays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musiccontainer',
            name='length',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
