# Generated by Django 5.0.2 on 2024-02-28 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root_user', '0006_alter_authusermodel_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authusermodel',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures'),
        ),
    ]
